sudo: required
language: python

python:
    - "3.5"
    - "3.6"

install:
    - sudo apt-get install xvfb
    - pip install -r requirements-dev.txt
    - pip install -e .

script:
    - python -m pytest -v
