language: python
os: linux
dist: xenial
sudo: required

python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get install libxkbcommon-x11-0

install:
  # exclude 5.10 on travis https://bugreports.qt.io/browse/QTBUG-64928
  - pip install "pyqt5!=5.10,!=5.12.0"
  - pip install -e .[dev]
  - pip install pytest-faulthandler codecov
  - pip list

script:
  - pytest -sv --cov axopy

after_success:
  - codecov
