name: axopy_docs

channels:
    - conda-forge

dependencies:
    - python>=3.4
    - h5py
    - numpy
    - scipy
    - pyqt>=5
    - sphinx
    - sphinx_rtd_theme
    - pip:
        - pyqtgraph>=0.10
        - git+https://github.com/ucdrascal/copper.git
